#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID    : "012409364995"
    IMAGE_REPO_NAME   : "stocks"
    IMAGE_TAG         : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t stocks:latest .
      - docker tag stocks:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stocks:latest
      - docker tag stocks:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stocks:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stocks:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stocks:$COMMIT_ID
