#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    AWS_ACCOUNT_ID    : "012409364995"
    AWS_CLUSTER_NAME  : "stocks-cluster"
    IMAGE_REPO_NAME   : "stocks_001"
    IMAGE_TAG         : "latest"


phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version
      - curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - sudo mv ./kubectl /usr/local/bin/kubectl
      - ./kubectl version --client

  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_ID=$(git rev-parse --short HEAD)

  build:
    commands:
      - echo Building the Docker image...
      - mvn package
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_ID
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
      - ./kubectl create deployment hello-minikube --image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - ./kubectl delete services hello-minikube