server:
  port: 8090
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    ddl-auto: none
    properties:
      hibernate:
        proc:
          param_null_passing: true
        generate_statistics: true
        jdbc:
          batch_size: 1000
  liquibase:
    change-log: classpath:db/scripts.xml
    enabled: true
logging:
  level:
    liquibase: ERROR
    root: INFO
app:
  limits:
    threadCount: 5
    timeout: 1000
    reportInterval: 5000
  report:
    timeout: ${REPORT_TIMEOUT}
  download:
    timeout: ${DOWNLOAD_TIMEOUT}
platform:
  iex:
    token: ${STOCK_TOKEN}
    url:
      quote: https://cloud.iexapis.com/stable/stock
      symbol: https://cloud.iexapis.com/stable/ref-data/symbols