server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/scripts.xml
logging:
  level:
    liquibase: ERROR
    root: INFO